config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments, only: [:create]
    resources :reactions, only: [:create]
  end
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user, optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :reactions, dependent: :destroy
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
  has_many :reactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :photo])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user unless comment_params[:anonymous] == '1'

    if @comment.save
      redirect_to @post, notice: 'Comentario hecho exitosamente.'
    else
      redirect_to @post, alert: 'El comentario no ha podido ser realizado.'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :anonymous)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  before_action :authenticate_user!
  def create
    @post = Post.find(params[:post_id])
    @reaction = @post.reactions.find_or_initialize_by(user: current_user)

    if @reaction.kind == params[:kind]
      redirect_to @post, alert: 'You have already reacted with this option.'
    else
      update_reaction_counts(@reaction, params[:kind])
      @reaction.update(kind: params[:kind])
      redirect_to @post, notice: 'Reaction updated successfully.'
    end
  end

  private

  def update_reaction_counts(reaction, new_kind)
    if reaction.kind == 'like'
      @post.decrement!(:likes_count)
    elsif reaction.kind == 'dislike'
      @post.decrement!(:dislikes_count)
    end

    if new_kind == 'like'
      @post.increment!(:likes_count)
    elsif new_kind == 'dislike'
      @post.increment!(:dislikes_count)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [ @post, @post.comments.build ], local: true) do |form| %>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  <div class="actions">
    <%= form.submit "Add Comment" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crazy4Cats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>

  <p>
    <strong>User:</strong>
    <%= post.user_id %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<div class="container mt-4">
  <h1 class="mb-4 text-center">All Crazy4Cats Posts</h1>

  <div class="row">
    <% @posts.each do |post| %>
      <div class="col-md-6 mb-4">
        <div class="card h-100">
          <div class="card-body">
            <h5 class="card-title"><%= link_to post.title, post_path(post), class: "text-decoration-none" %></h5>
            <p class="card-text">
              <%= truncate(post.content, length: 100) %>
            </p>
            <p class="text-muted">
              Posted by: <%= post.user&.name || "Anonymous" %>
            </p>
            <%= link_to 'Leer mas', post_path(post), class: 'btn btn-primary' %>
          </div>
          <div class="card-footer text-muted">
            <span>Likes: <%= post.likes_count || 0 %></span> |
            <span>Dislikes: <%= post.dislikes_count || 0 %></span>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="text-center">
    <%= link_to 'New Post', new_post_path, class: 'btn btn-success mt-4' if user_signed_in? %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">

  <h1>Titular: <%= @post.title %></h1>
  <p><b>Post:</b> <%= @post.content %></p>

  <hr>

  <h4>Reactions</h4>
  <p>Likes: <%= @post.likes_count || 0 %> | Dislikes: <%= @post.dislikes_count || 0 %></p>

  <div class="d-flex gap-2">
    <% unless @post.reactions.find_by(user: current_user)&.kind == 'like' %>
      <%= button_to 'Like', post_reactions_path(@post, kind: 'like'), method: :post, class: 'btn btn-success' %>
    <% end %>

    <% unless @post.reactions.find_by(user: current_user)&.kind == 'dislike' %>
      <%= button_to 'Dislike', post_reactions_path(@post, kind: 'dislike'), method: :post, class: 'btn btn-danger' %>
    <% end %>
  </div>


  <h3>Comments</h3>
  <%= form_with model: [@post, @post.comments.build], local: true do |f| %>
  <div class="mb-3">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control' %>
  </div>

  <div class="form-check mb-3">
    <%= f.check_box :anonymous, class: 'form-check-input' %>
    <%= f.label :anonymous, 'Comment as Anonymous', class: 'form-check-label' %>
  </div>

  <div class="actions">
    <%= f.submit 'Add Comment', class: 'btn btn-primary' %>
  </div>
  <% end %>

  <hr>

  <h4>Existing Comments</h4>
  <% @comments.each do |comment| %>
  <div class="comment-box mb-3">
    <strong><%= comment.anonymous? ? "Anonymous" : comment.user&.email || "Unknown User" %>:</strong>
    <p><%= comment.content %></p>
  </div>
  <% end %>
  

  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">Crazy4Cats</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Pagina Principal', root_path, class: 'nav-link' %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Nuevo Post', new_post_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Cerrar Sesion', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Iniciar Sesion', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Registrarse', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>